debug: "debug"

http:
  addr: ":8210"
  read_timeout: 10
  write_timeout: 10
  max_header_bytes: 20

swagger:
  title: "定时任务服务swagger API"
  desc: "这是一个简单的定时任务执行系统"
  host: "127.0.0.1:8200"
  base_path: ""

db:
  engine: "mysql"
  host: "10.10.8.252"
  port: 3306
  name: "cronJob"
  user: "root"
  password: "marco@123"